# Generated by Django 5.1.3 on 2024-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_projects',
            field=models.ManyToManyField(blank=True, related_name='current_users', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_history',
            field=models.ManyToManyField(blank=True, related_name='historical_users', to='projects.project'),
        ),
    ]
